## Include rules/common first as this file only defines input target
## functions and common configuration for the workflow
include: "rules/common.smk"


# rule all:
#    input:
#        unpack(fasta_inputs),
#        unpack(af_targets),
rule all:
    input:
        unpack(all_input),


checkpoint check_mail:
    input:
        unpack(fasta_inputs),


rule run_all_af:
    input:
        unpack(af_targets),


rule upload_all:
    input:
        unpack(uploads),


rule upload_msas:
    input:
        unpack(msa_uploads),


rule upload_models:
    input:
        unpack(model_uploads),


##############################
## Included rules
##############################
include: "rules/alphafold.smk"
include: "rules/submit.smk"
include: "rules/upload.smk"
